apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  namespace: default
  name: DeveloperRoleBinding
subjects:
  - kind: ServiceAccount
    name: demo
    namespace: default
roleRef:
  kind: ClusterRole
  name: Developer
  apiGroup: rbac.authorization.k8s.io
