apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-reader-binding
  namespace: bassa
roleRef: # points to the ClusterRole
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pod-reader # name of ClusterRole
subjects: # points to the ServiceAccount
- kind: ServiceAccount
  name: bassa-serviceaccount # service account to bind to
  namespace: bassa # ns of service account
